apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-of-apps
  namespace: argocd 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # TODO: Replace with your actual Git repository URL
    repoURL: 'https://github.com/DayongLu/istio-clusters.git'
    targetRevision: main
    # This points to the folder containing your child apps
    path: apps
  destination:
    # The root app ALWAYS deploys to the same cluster Argo CD is running on
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true     # Removes apps if you delete their YAML from Git
      selfHeal: true  # Fixes manual changes made via UI/CLI